version: '3.3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/srv/public:ro
    depends_on:
      - app

  app:
    build:
      context: ./
    volumes:
      - ./:/srv
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=workshop

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    environment:
      - server.host=0.0.0.0

  mailcatcher:
    image: jeanberu/mailcatcher

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
